// frontend-next/src/app/search/page.tsx
'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import {
  Box,
  Button,
  Card,
  CardActionArea,
  CardContent,
  Chip,
  Container,
  Dialog,
  DialogContent,
  Grid,
  IconButton,
  Skeleton,
  TextField,
  Typography,
  useMediaQuery,
  useTheme,
} from '@mui/material';
import {
  Close as CloseIcon,
  Psychology as SmartSearchIcon,
  SmartToy as AIIcon,
} from '@mui/icons-material';
import { newsService } from '@/services/newsService';
import { News } from '@/types';
import NewsDetail from '@/components/NewsDetail';
import { getCategoryLabel } from '@/utils/getCategoryLabel';
import { formatAppliedFilters } from '@/utils/formatAppliedFilters';
import { truncateText } from '@/utils/truncateText';

const PAGE_SIZE = 20;

const EXAMPLE_QUERIES = [
  'AI новости про технологии за неделю',
  'экономика и инфляция',
  'популярные новости про спорт',
];

export default function SmartSearchPage() {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));
  const [query, setQuery] = useState('');
  const [activeQuery, setActiveQuery] = useState<string | null>(null);
  const [news, setNews] = useState<News[]>([]);
  const [loading, setLoading] = useState(false);
  const [loadingMore, setLoadingMore] = useState(false);
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(false);
  const [searchHint, setSearchHint] = useState<string | null>(null);
  const [searchSource, setSearchSource] = useState<'ai' | 'fallback' | null>(null);
  const [selectedNews, setSelectedNews] = useState<News | null>(null);
  const loaderRef = useRef<HTMLDivElement>(null);

  const applyResponse = useCallback(
    (
      data: Awaited<ReturnType<typeof newsService.smartSearch>>,
      pageNum: number,
      append: boolean,
    ) => {
      if (append) {
        setNews((prev) => [...prev, ...data.data]);
      } else {
        setNews(data.data);
      }
      setHasMore(pageNum * PAGE_SIZE < data.total);
      setSearchHint(formatAppliedFilters(data.appliedFilters));
      setSearchSource(data.source);
    },
    [],
  );

  const runSearch = useCallback(
    async (searchQuery: string, pageNum: number, append: boolean) => {
      if (append) {
        setLoadingMore(true);
      } else {
        setLoading(true);
      }

      try {
        const data = await newsService.smartSearch(searchQuery, pageNum, PAGE_SIZE);
        applyResponse(data, pageNum, append);
      } catch {
        if (!append) {
          setNews([]);
          setHasMore(false);
          setSearchHint(null);
          setSearchSource(null);
        }
      }

      setLoading(false);
      setLoadingMore(false);
    },
    [applyResponse],
  );

  const handleSearch = () => {
    const trimmed = query.trim();
    if (!trimmed) return;

    setActiveQuery(trimmed);
    setPage(1);
    setHasMore(true);
    runSearch(trimmed, 1, false);
  };

  useEffect(() => {
    if (!activeQuery) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && hasMore && !loading && !loadingMore) {
          const nextPage = page + 1;
          setPage(nextPage);
          runSearch(activeQuery, nextPage, true);
        }
      },
      { threshold: 0.1 },
    );

    if (loaderRef.current) {
      observer.observe(loaderRef.current);
    }

    return () => observer.disconnect();
  }, [activeQuery, hasMore, loading, loadingMore, page, runSearch]);

  return (
    <Container sx={{ py: { xs: 2, md: 4 }, px: { xs: 1, sm: 2 }, maxWidth: '100%', minWidth: 0 }}>
      <Typography variant="h4" gutterBottom sx={{ fontSize: { xs: '1.3rem', sm: '2rem' } }}>
        🧠 Умный поиск
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
        Опишите запрос своими словами — AI подберёт фильтры, а поиск выполнится по заголовку,
        описанию и тегам.
      </Typography>

      <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', mb: 2 }}>
        <TextField
          fullWidth={isMobile}
          multiline={!isMobile}
          minRows={isMobile ? 1 : 2}
          size="small"
          placeholder="Например: AI новости про технологии за последнюю неделю"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault();
              handleSearch();
            }
          }}
          sx={{ flex: 1, minWidth: isMobile ? '100%' : 320 }}
        />
        <Button
          variant="contained"
          onClick={handleSearch}
          disabled={!query.trim() || loading}
          startIcon={<SmartSearchIcon />}
        >
          Найти
        </Button>
      </Box>

      <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', mb: 3 }}>
        {EXAMPLE_QUERIES.map((example) => (
          <Chip
            key={example}
            label={example}
            variant="outlined"
            onClick={() => {
              setQuery(example);
            }}
          />
        ))}
      </Box>

      {searchHint && (
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          Распознано{searchSource === 'fallback' ? ' (без AI)' : ''}: {searchHint}
        </Typography>
      )}

      {!activeQuery && !loading && (
        <Typography variant="body2" color="text.secondary">
          Введите запрос и нажмите «Найти».
        </Typography>
      )}

      <Grid container spacing={1.5} sx={{ mt: 1 }}>
        {loading
          ? Array.from({ length: 4 }).map((_, i) => (
              <Grid size={{ xs: 12 }} key={i}>
                <Card>
                  <CardContent>
                    <Skeleton variant="text" height={24} />
                    <Skeleton variant="text" />
                    <Skeleton variant="text" width="40%" />
                  </CardContent>
                </Card>
              </Grid>
            ))
          : news.map((item) => (
              <Grid size={{ xs: 12 }} key={item.id}>
                <Card>
                  <CardActionArea onClick={() => setSelectedNews(item)}>
                    <CardContent
                      sx={{ py: { xs: 1.5, sm: 2 }, '&:last-child': { pb: { xs: 1.5, sm: 2 } } }}
                    >
                      <Typography
                        variant="subtitle1"
                        sx={{
                          fontWeight: 600,
                          fontSize: { xs: '0.9rem', sm: '1rem' },
                          wordBreak: 'break-word',
                        }}
                      >
                        {item.title}
                      </Typography>
                      <Typography
                        variant="body2"
                        color="text.secondary"
                        sx={{
                          mb: 1,
                          fontSize: { xs: '0.75rem', sm: '0.875rem' },
                          wordBreak: 'break-word',
                        }}
                      >
                        {truncateText(item.summary, 150)}
                      </Typography>
                      <Box
                        sx={{ display: 'flex', gap: 0.5, alignItems: 'center', flexWrap: 'wrap' }}
                      >
                        <Chip
                          label={getCategoryLabel(item.category)}
                          size="small"
                          color="primary"
                          variant="outlined"
                        />
                        {item.isAiGenerated && (
                          <Chip icon={<AIIcon />} label="AI" size="small" color="secondary" />
                        )}
                        <Typography
                          variant="caption"
                          color="text.secondary"
                          sx={{ ml: 'auto', whiteSpace: 'nowrap' }}
                        >
                          👁 {item.views} · ❤️ {item.likes} ·{' '}
                          {new Date(item.publishedAt ?? item.createdAt).toLocaleDateString('ru-RU')}
                        </Typography>
                      </Box>
                    </CardContent>
                  </CardActionArea>
                </Card>
              </Grid>
            ))}
      </Grid>

      {activeQuery && !loading && news.length === 0 && (
        <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
          По запросу «{activeQuery}» ничего не найдено.
        </Typography>
      )}

      <div ref={loaderRef} style={{ textAlign: 'center', padding: '24px 0' }}>
        {loadingMore && <Skeleton variant="text" width={200} sx={{ mx: 'auto' }} />}
        {!hasMore && news.length > 0 && (
          <Typography variant="body2" color="text.secondary">
            Все результаты загружены
          </Typography>
        )}
      </div>

      <Dialog
        open={!!selectedNews}
        onClose={() => setSelectedNews(null)}
        maxWidth="md"
        fullWidth
        fullScreen={isMobile}
      >
        <IconButton
          onClick={() => setSelectedNews(null)}
          sx={{ position: 'absolute', right: 8, top: 8, zIndex: 1 }}
        >
          <CloseIcon />
        </IconButton>
        <DialogContent sx={{ p: { xs: 2, sm: 3 } }}>
          {selectedNews && <NewsDetail news={selectedNews} />}
        </DialogContent>
      </Dialog>
    </Container>
  );
}

// frontend-nuxt/app/pages/search/index.vue
<template>
  <div class="search-page">
    <h1 class="page-title">🧠 Умный поиск</h1>
    <p class="page-description">
      Опишите запрос своими словами — AI подберёт фильтры, а поиск выполнится по заголовку, описанию
      и тегам.
    </p>

    <div class="search-form">
      <Textarea
        v-model="query"
        rows="3"
        auto-resize
        placeholder="Например: AI новости про технологии за последнюю неделю"
        class="search-input"
        @keydown.enter.exact.prevent="handleSearch"
      />
      <Button
        label="Найти"
        icon="pi pi-sparkles"
        :loading="loading"
        :disabled="!query.trim()"
        @click="handleSearch"
      />
    </div>

    <div class="examples">
      <Chip
        v-for="example in exampleQueries"
        :key="example"
        :label="example"
        class="example-chip"
        @click="query = example"
      />
    </div>

    <p v-if="searchHint" class="search-hint">
      Распознано<span v-if="searchSource === 'fallback'"> (без AI)</span>: {{ searchHint }}
    </p>

    <p v-if="!activeQuery && !loading" class="search-placeholder">
      Введите запрос и нажмите «Найти».
    </p>

    <div v-if="loading" class="loading-container">
      <ProgressSpinner />
    </div>

    <div v-else-if="news.length" class="news-grid">
      <NewsCard v-for="item in news" :key="item.id" :news="item" @click="openNewsDetail" />
    </div>

    <div v-else-if="activeQuery" class="empty-state">
      <i class="pi pi-search" style="font-size: 3rem; color: var(--p-text-muted-color)"></i>
      <h3>По запросу «{{ activeQuery }}» ничего не найдено</h3>
    </div>

    <div ref="loaderRef" class="load-more">
      <ProgressSpinner v-if="loadingMore" style="width: 32px; height: 32px" />
      <span v-else-if="!hasMore && news.length">Все результаты загружены</span>
    </div>

    <NewsDetailModal
      v-if="detailModalVisible"
      v-model:visible="detailModalVisible"
      :news="selectedNews"
    />
  </div>
</template>

<script setup lang="ts">
import type { NewsItem } from '~/types';
import { getErrorMessage } from '~/utils/getErrorMessage';
import { useNewsService } from '~/services/news.service.ts';

const PAGE_SIZE = 20;
const { formatAppliedFilters } = useUtils();

const exampleQueries = [
  'AI новости про технологии за неделю',
  'экономика и инфляция',
  'популярные новости про спорт',
];

const newsService = useNewsService();
const { showError } = useAppToast();

const query = ref('');
const activeQuery = ref<string | null>(null);
const news = ref<NewsItem[]>([]);
const loading = ref(false);
const loadingMore = ref(false);
const page = ref(1);
const hasMore = ref(false);
const searchHint = ref<string | null>(null);
const searchSource = ref<'ai' | 'fallback' | null>(null);
const detailModalVisible = ref(false);
const selectedNews = ref<NewsItem | null>(null);
const loaderRef = ref<HTMLElement | null>(null);

let observer: IntersectionObserver | null = null;

useHead({
  title: 'Умный поиск',
  meta: [{ name: 'description', content: 'AI-поиск новостей по естественному языку.' }],
});

async function runSearch(searchQuery: string, pageNum: number, append: boolean) {
  if (append) {
    loadingMore.value = true;
  } else {
    loading.value = true;
  }

  try {
    const data = await newsService.smartSearch(searchQuery, pageNum, PAGE_SIZE);
    news.value = append ? [...news.value, ...data.data] : data.data;
    hasMore.value = pageNum * PAGE_SIZE < data.total;
    searchHint.value = formatAppliedFilters(data.appliedFilters);
    searchSource.value = data.source;
  } catch (error: unknown) {
    if (!append) {
      news.value = [];
      hasMore.value = false;
      searchHint.value = null;
      searchSource.value = null;
    }
    showError(getErrorMessage(error, 'Не удалось выполнить поиск'));
  } finally {
    loading.value = false;
    loadingMore.value = false;
    await nextTick();
    setupObserver();
  }
}

function handleSearch() {
  const trimmed = query.value.trim();
  if (!trimmed) return;

  activeQuery.value = trimmed;
  page.value = 1;
  hasMore.value = true;
  runSearch(trimmed, 1, false);
}

function openNewsDetail(id: string) {
  selectedNews.value = news.value.find((item) => item.id === id) || null;
  if (selectedNews.value) {
    detailModalVisible.value = true;
  }
}

function setupObserver() {
  observer?.disconnect();
  if (!loaderRef.value || !activeQuery.value) return;

  observer = new IntersectionObserver(
    (entries) => {
      if (entries[0]?.isIntersecting && hasMore.value && !loading.value && !loadingMore.value) {
        const nextPage = page.value + 1;
        page.value = nextPage;
        runSearch(activeQuery.value!, nextPage, true);
      }
    },
    { threshold: 0.1 },
  );
  observer.observe(loaderRef.value);
}

onMounted(() => {
  setupObserver();
});

onUnmounted(() => {
  observer?.disconnect();
});
</script>

<style scoped>
.search-page {
  max-width: 960px;
  margin: 0 auto;
}

.page-title {
  font-size: 2rem;
  font-weight: 700;
  margin-bottom: 0.75rem;
}

.page-description {
  color: var(--p-text-muted-color);
  margin-bottom: 1.5rem;
  line-height: 1.6;
}

.search-form {
  display: flex;
  gap: 0.75rem;
  flex-wrap: wrap;
  margin-bottom: 1rem;
}

.search-input {
  flex: 1;
  min-width: 280px;
}

.examples {
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
  margin-bottom: 1.5rem;
}

.example-chip {
  cursor: pointer;
}

.search-hint,
.search-placeholder {
  color: var(--p-text-muted-color);
  margin-bottom: 1rem;
}

.news-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1rem;
  margin-bottom: 1rem;
}

.loading-container,
.load-more {
  display: flex;
  justify-content: center;
  padding: 2rem 0;
}

.load-more span {
  color: var(--p-text-muted-color);
}

.empty-state {
  text-align: center;
  padding: 3rem 1rem;
  color: var(--p-text-muted-color);
}

.empty-state h3 {
  margin-top: 1rem;
  color: var(--p-text-color);
  font-size: 1.1rem;
}

@media (max-width: 768px) {
  .page-title {
    font-size: 1.5rem;
  }

  .search-form {
    flex-direction: column;
  }

  .search-input {
    width: 100%;
    min-width: unset;
  }
}
</style>
