// frontend-nuxt/app/components/news/NewsDetailModal.vue
<template>
  <Dialog
    v-model:visible="visible"
    :modal="true"
    :header="news?.title"
    class="dialog-width-news-detail"
    :breakpoints="{ '768px': '95vw' }"
    :closable="true"
    :dismissable-mask="true"
  >
    <div v-if="news" class="news-detail">
      <div v-if="news.imageUrl" class="detail-image">
        <img :src="news.imageUrl" :alt="news.title" loading="lazy" decoding="async" />
      </div>

      <div class="detail-meta">
        <span class="meta-badge">
          <i class="pi pi-tag"></i>
          {{ categoryLabel }}
        </span>
        <span class="meta-item">
          <i class="pi pi-eye"></i>
          {{ news.views }} просмотров
        </span>
        <span class="meta-item">
          <i class="pi pi-calendar"></i>
          {{ formatDate(news.publishedAt || news.createdAt) }}
        </span>
        <span v-if="news.source" class="meta-item">
          <i class="pi pi-globe"></i>
          {{ news.source }}
        </span>
      </div>

      <div v-if="authorUser" class="detail-author">
        <Avatar :label="getAuthorInitials(authorUser)" class="avatar-primary" shape="circle" />
        <div>
          <p class="author-name">{{ authorUser.firstName }} {{ authorUser.lastName }}</p>
          <p class="author-username">@{{ authorUser.username }}</p>
        </div>
      </div>

      <div class="detail-content" v-html="news.content"></div>

      <div v-if="news.tags?.length" class="detail-tags">
        <span v-for="tag in news.tags" :key="tag" class="news-tag news-tag--md">#{{ tag }}</span>
      </div>

      <div class="detail-actions">
        <Button
          :icon="news.isLiked ? 'pi pi-heart-fill' : 'pi pi-heart'"
          :label="`${news.likes}`"
          :aria-label="`${news.likes}`"
          :severity="news.isLiked ? 'danger' : 'secondary'"
          :disabled="!authStore.isAuthenticated"
          @click="handleLike"
        />
        <Button
          :icon="news.isFavorite ? 'pi pi-star-fill' : 'pi pi-star'"
          :label="news.isFavorite ? 'В избранном' : 'В избранное'"
          :aria-label="news.isFavorite ? 'В избранном' : 'В избранное'"
          :severity="news.isFavorite ? 'warning' : 'secondary'"
          :disabled="!authStore.isAuthenticated"
          @click="handleToggleFavorite"
        />
        <Button
          icon="pi pi-share-alt"
          label="Поделиться"
          aria-label="Поделиться"
          severity="info"
          @click="shareNews"
        />
      </div>

      <div v-if="news.sourceUrl" class="detail-source">
        <a :href="news.sourceUrl" target="_blank" rel="noopener noreferrer">
          <i class="pi pi-external-link"></i>
          Читать оригинал
        </a>
      </div>
    </div>
  </Dialog>
</template>

<script setup lang="ts">
import type { NewsItem, UserResponse } from '~/types';
import { useNewsService } from '~/services/news.service.ts';

const props = defineProps<{
  news: NewsItem | null;
  visible: boolean;
}>();

const emit = defineEmits<{
  'update:visible': [value: boolean];
  like: [id: string];
  favorite: [id: string];
}>();

const authStore = useAuthStore();
const newsStore = useNewsStore();
const newsService = useNewsService();
const { showSuccess, showWarning } = useAppToast();

watch(
  () => (props.visible && props.news?.id ? props.news.id : ''),
  (id) => {
    if (!id) return;
    void newsService.getNewsById(id).catch(() => {});
  },
  { immediate: true },
);

const visible = computed({
  get: () => props.visible,
  set: (value) => emit('update:visible', value),
});

const categoryLabel = computed(() => {
  if (!props.news) return '';
  const labels: Record<string, string> = {
    politics: 'Политика',
    economy: 'Экономика',
    technology: 'Технологии',
    science: 'Наука',
    sports: 'Спорт',
    entertainment: 'Развлечения',
    health: 'Здоровье',
    world: 'Мир',
    other: 'Другое',
  };
  return labels[props.news.category] || props.news.category;
});

const authorUser = computed((): UserResponse | null => props.news?.author ?? null);

function getAuthorInitials(author: UserResponse): string {
  const first = author.firstName?.[0] || author.username[0];
  const last = author.lastName?.[0] || '';
  return (first + last).toUpperCase();
}

async function handleLike() {
  if (!props.news) return;

  if (!authStore.isAuthenticated) {
    showWarning('Войдите, чтобы ставить лайки', 'Требуется авторизация');
    return;
  }

  try {
    await newsStore.likeNews(props.news.id);
    emit('like', props.news.id);
  } catch (error) {
    console.error('Error liking news:', error);
  }
}

async function handleToggleFavorite() {
  if (!props.news) return;

  if (!authStore.isAuthenticated) {
    showWarning('Войдите, чтобы добавлять в избранное', 'Требуется авторизация');
    return;
  }

  try {
    await newsStore.toggleFavorite(props.news.id);
    emit('favorite', props.news.id);
  } catch (error) {
    console.error('Error toggling favorite:', error);
  }
}

async function shareNews() {
  if (!props.news) return;

  const shareData = {
    title: props.news.title,
    text: props.news.summary || props.news.title,
    url: window.location.href,
  };

  try {
    if (navigator.share) {
      await navigator.share(shareData);
    } else {
      await navigator.clipboard.writeText(window.location.href);
      showSuccess('Ссылка на новость скопирована в буфер обмена', 'Ссылка скопирована');
    }
  } catch (error) {
    console.error('Error sharing:', error);
  }
}

function formatDate(date: string): string {
  return new Date(date).toLocaleDateString('ru-RU', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}
</script>

<style scoped>
.news-detail {
  padding: 0;
}

.detail-image {
  width: 100%;
  max-height: 400px;
  overflow: hidden;
  border-radius: 6px;
  margin-bottom: 1.5rem;
}

.detail-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.detail-meta {
  display: flex;
  gap: 1rem;
  flex-wrap: wrap;
  margin-bottom: 1rem;
}

.meta-badge {
  background-color: var(--p-primary-color);
  color: white;
  padding: 0.25rem 0.75rem;
  border-radius: 20px;
  font-size: 0.75rem;
  font-weight: 600;
  display: flex;
  align-items: center;
  gap: 0.25rem;
}

.meta-item {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  color: var(--p-text-muted-color);
  font-size: 0.875rem;
}

.detail-author {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 1rem;
  background-color: var(--p-surface-hover);
  border-radius: 6px;
  margin-bottom: 1.5rem;
}

.author-name {
  font-weight: 600;
  color: var(--p-text-color);
}

.author-username {
  color: var(--p-text-muted-color);
  font-size: 0.875rem;
}

.detail-content {
  line-height: 1.8;
  color: var(--p-text-color);
  margin-bottom: 1.5rem;
}

.detail-content :deep(p) {
  margin-bottom: 1rem;
}

.detail-tags {
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
  margin-bottom: 1.5rem;
}

.detail-actions {
  display: flex;
  gap: 0.75rem;
  flex-wrap: wrap;
  padding: 1rem 0;
  border-top: 1px solid var(--p-surface-border);
  border-bottom: 1px solid var(--p-surface-border);
  margin-bottom: 1rem;
}

.detail-source {
  text-align: center;
  padding: 0.5rem 0;
}

.detail-source a {
  color: var(--p-primary-color);
  text-decoration: none;
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  font-weight: 500;
}

.detail-source a:hover {
  text-decoration: underline;
}

@media (max-width: 768px) {
  .detail-image {
    max-height: 250px;
  }

  .detail-actions {
    flex-direction: column;
  }
}
</style>

// frontend-ssr/src/components/NewsDetailModal.tsx
import React, { useEffect, useState } from 'react';
import {
  Spin,
  Typography,
  Tag,
  Space,
  Divider,
  Image,
  Alert,
  Button,
  message,
} from 'antd';
import {
  ClockCircleOutlined,
  EyeOutlined,
  HeartOutlined,
  HeartFilled,
  RobotOutlined,
  LinkOutlined,
  UserOutlined,
  ShareAltOutlined,
  LikeFilled,
  LikeOutlined,
} from '@ant-design/icons';
import { newsService } from '../services/news.service';
import type { News } from '../types';
import { useUserStore } from '../store/userStoreProvider';

const { Title, Text, Paragraph } = Typography;

const NewsDetailModal: React.FC<{ newsId: string }> = ({ newsId }) => {
  const [news, setNews] = useState<News | null>(null);
  const user = useUserStore((s) => s.user);
  const [loading, setLoading] = useState(true);
  const [isFavorited, setIsFavorited] = useState(false);
  const [isLiked, setIsLiked] = useState(false);
  const [likesCount, setLikesCount] = useState(0);

  useEffect(() => {
    loadNews();
  }, [newsId]);

  const loadNews = async () => {
    setLoading(true);
    try {
      const data = await newsService.fetchById(newsId);
      setNews(data);
      setLikesCount(data.likes || 0);
    } catch {
      message.error('Ошибка загрузки новостей');
    }
    checkLike();
    checkFavorite();
    setLoading(false);
  };

  const checkLike = async () => {
    if (!user) return;
    try {
      const liked = await newsService.isLiked(newsId);
      setIsLiked(liked);
    } catch {
      message.error('Ошибка запроса checkLike');
    }
  };

  const checkFavorite = async () => {
    if (!user) return;
    try {
      const favorited = await newsService.isFavorited(newsId);
      setIsFavorited(favorited);
    } catch {
      message.error('Ошибка запроса checkFavorite');
    }
  };

  const handleLike = async () => {
    if (!user) {
      message.info('Войдите, чтобы ставить лайки');
      return;
    }
    try {
      const result = await newsService.toggleLike(newsId);
      setIsLiked(result.liked);
      setLikesCount(result.likes);
    } catch {
      message.error('Ошибка');
    }
  };

  const handleToggleFavorite = async () => {
    const token = localStorage.getItem('accessToken');
    if (!token) {
      message.info('Войдите, чтобы добавлять в избранное');
      return;
    }
    try {
      const result = await newsService.toggleFavorite(newsId);
      setIsFavorited(result.favorited);
      message.success(
        result.favorited ? 'Добавлено в избранное' : 'Удалено из избранного',
      );
    } catch {
      message.error('Ошибка');
    }
  };

  const handleShare = async () => {
    if (news) {
      const url = `${window.location.origin}/?news=${news.id}`;
      try {
        await navigator.share({ title: news.title, text: news.summary, url });
      } catch {
        await navigator.clipboard.writeText(url);
        message.success('Ссылка скопирована');
      }
    }
  };

  if (loading)
    return (
      <div style={{ textAlign: 'center', padding: 40 }}>
        <Spin size="large" />
      </div>
    );
  if (!news) return <div>Новость не найдена</div>;

  const getCategoryColor = (cat: string) => {
    const colors: Record<string, string> = {
      politics: 'blue',
      economy: 'green',
      technology: 'purple',
      science: 'cyan',
      sports: 'orange',
      entertainment: 'magenta',
      health: 'red',
      world: 'geekblue',
    };
    return colors[cat] || 'default';
  };

  const getCategoryLabel = (cat: string) => {
    const labels: Record<string, string> = {
      politics: 'Политика',
      economy: 'Экономика',
      technology: 'Технологии',
      science: 'Наука',
      sports: 'Спорт',
      entertainment: 'Развлечения',
      health: 'Здоровье',
      world: 'Мир',
    };
    return labels[cat] || cat;
  };

  return (
    <div>
      <Alert
        title={
          news.isAiGenerated
            ? '🤖 AI-рерайт новости'
            : '📄 Оригинальная новость'
        }
        description={
          news.isAiGenerated
            ? 'Эта новость создана с помощью искусственного интеллекта на основе реальных данных. Факты сохранены, формулировки изменены.'
            : 'Оригинальная новость из новостного источника.'
        }
        type={news.isAiGenerated ? 'info' : 'success'}
        showIcon
        style={{ marginBottom: 16 }}
      />
      <Title level={3}>{news.title}</Title>
      <Space wrap size="middle" style={{ marginBottom: 16, color: '#666' }}>
        <Text type="secondary">
          <ClockCircleOutlined />{' '}
          {new Date(news.publishedAt).toLocaleDateString('ru-RU', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
          })}
        </Text>
        <Text type="secondary">
          <EyeOutlined /> {news.views || 0} просмотров
        </Text>
        {news.author && (
          <Text type="secondary">
            <UserOutlined /> {news.author}
          </Text>
        )}
      </Space>

      <Space style={{ marginBottom: 16 }}>
        <Button
          icon={isLiked ? <LikeFilled /> : <LikeOutlined />}
          onClick={handleLike}
          size="small"
          danger={isLiked}
        >
          {likesCount || news.likes || 0}
        </Button>
        <Button
          icon={isFavorited ? <HeartFilled /> : <HeartOutlined />}
          onClick={handleToggleFavorite}
          size="small"
          type={isFavorited ? 'primary' : 'default'}
          danger={isFavorited}
        >
          {isFavorited ? 'В избранном' : 'В избранное'}
        </Button>
        <Button icon={<ShareAltOutlined />} onClick={handleShare} size="small">
          Поделиться
        </Button>
      </Space>

      <Space wrap style={{ marginBottom: 16 }}>
        <Tag color={getCategoryColor(news.category)}>
          {getCategoryLabel(news.category)}
        </Tag>
        {news.isAiGenerated ? (
          <Tag icon={<RobotOutlined />} color="blue">
            AI-рерайт
          </Tag>
        ) : (
          <Tag icon={<LinkOutlined />} color="green">
            Оригинал
          </Tag>
        )}
        {news.source && <Tag color="purple">{news.source}</Tag>}
        {news.tags?.map((tag) => (
          <Tag key={tag}>{tag}</Tag>
        ))}
      </Space>

      <Divider />
      {news.imageUrl && (
        <Image
          src={news.imageUrl}
          style={{
            width: '100%',
            maxHeight: 400,
            objectFit: 'cover',
            borderRadius: 8,
            marginBottom: 16,
          }}
          fallback="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="
        />
      )}
      {news.summary && (
        <Paragraph strong style={{ fontSize: 16, marginBottom: 16 }}>
          {news.summary}
        </Paragraph>
      )}
      <div
        dangerouslySetInnerHTML={{ __html: news.content }}
        style={{ fontSize: 15, lineHeight: 1.8, textAlign: 'justify' }}
      />
      {news.sourceUrl && (
        <div style={{ marginTop: 16 }}>
          <a href={news.sourceUrl} target="_blank" rel="noopener noreferrer">
            Читать оригинал на {news.source || 'источнике'}
          </a>
        </div>
      )}
    </div>
  );
};

export default NewsDetailModal;
