// frontend-vue/src/components/news/NewsDetailModal.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { newsService } from '@/services/news.service';
import { useAuthStore } from '@/stores/auth';
import type { News } from '@/types/news';

const props = defineProps<{ news: News }>();
const emit = defineEmits<{ close: [] }>();

const authStore = useAuthStore();
const isLiked = ref(false);
const isFavorited = ref(false);
const likesCount = ref(props.news.likes || 0);
const fullNews = ref<News | null>(null);
const loading = ref(true);
const snackbar = ref('');

onMounted(async () => {
  try {
    fullNews.value = await newsService.getNewsById(props.news.id);
    likesCount.value = fullNews.value.likes || 0;
  } catch {}
  loading.value = false;
  checkState();
});

async function checkState() {
  if (!authStore.isAuthenticated) return;
  try {
    const [liked, favorited] = await Promise.all([newsService.isLiked(props.news.id), newsService.isFavorited(props.news.id)]);
    isLiked.value = liked;
    isFavorited.value = favorited;
  } catch {}
}

async function handleLike() {
  if (!authStore.isAuthenticated) {
    snackbar.value = 'Войдите, чтобы ставить лайки';
    return;
  }
  try {
    const result = await newsService.toggleLike(props.news.id);
    isLiked.value = result.liked;
    likesCount.value = result.likes;
  } catch {}
}

async function handleFavorite() {
  if (!authStore.isAuthenticated) {
    snackbar.value = 'Войдите, чтобы добавлять в избранное';
    return;
  }
  try {
    const result = await newsService.toggleFavorite(props.news.id);
    isFavorited.value = result.favorited;
  } catch {}
}

async function handleShare() {
  const url = `${window.location.origin}/?news=${props.news.id}`;
  try {
    await navigator.share({ title: props.news.title, text: props.news.summary, url });
  } catch {
    await navigator.clipboard.writeText(url);
    snackbar.value = 'Ссылка скопирована';
  }
}
</script>

<template>
  <v-card v-if="fullNews || !loading">
    <v-card-item>
      <v-alert :type="fullNews?.isAiGenerated ? 'info' : 'success'" :text="fullNews?.isAiGenerated ? '🤖 AI-рерайт новости' : '📄 Оригинальная новость'" variant="tonal" class="mb-4" />
      <v-card-title class="text-h5">{{ fullNews?.title }}</v-card-title>
      <v-card-subtitle class="mt-2">
        <span class="mr-4">📅 {{ new Date(fullNews?.publishedAt || '').toLocaleDateString('ru-RU') }}</span>
        <span class="mr-4">👁 {{ fullNews?.views || 0 }}</span>
        <span v-if="fullNews?.author">✍️ {{ fullNews.author }}</span>
      </v-card-subtitle>
    </v-card-item>

    <v-card-actions>
      <v-btn :prepend-icon="isLiked ? 'mdi-thumb-up' : 'mdi-thumb-up-outline'" :color="isLiked ? 'primary' : undefined" @click="handleLike">{{ likesCount }}</v-btn>
      <v-btn :prepend-icon="isFavorited ? 'mdi-heart' : 'mdi-heart-outline'" :color="isFavorited ? 'error' : undefined" @click="handleFavorite">{{
        isFavorited ? 'В избранном' : 'В избранное'
      }}</v-btn>
      <v-btn prepend-icon="mdi-share-variant" @click="handleShare">Поделиться</v-btn>
    </v-card-actions>

    <v-card-text>
      <div class="d-flex flex-wrap gap-2 mb-4">
        <v-chip color="primary" size="small">{{ fullNews?.category }}</v-chip>
        <v-chip v-if="fullNews?.isAiGenerated" color="secondary" size="small">AI-рерайт</v-chip>
        <v-chip v-if="fullNews?.source" variant="outlined" size="small">{{ fullNews.source }}</v-chip>
      </div>

      <v-img v-if="fullNews?.imageUrl" :src="fullNews.imageUrl" height="400" cover class="mb-4 rounded" />

      <p class="text-body-1 font-weight-medium mb-4" v-if="fullNews?.summary">{{ fullNews.summary }}</p>
      <div v-html="fullNews?.content" class="text-body-1" />

      <a v-if="fullNews?.sourceUrl" :href="fullNews.sourceUrl" target="_blank" class="d-block mt-4 text-primary">Читать оригинал на {{ fullNews.source || 'источнике' }}</a>
    </v-card-text>

    <v-card-actions>
      <v-spacer />
      <v-btn @click="emit('close')">Закрыть</v-btn>
    </v-card-actions>
  </v-card>

  <v-card v-else class="pa-8 text-center">
    <v-progress-circular indeterminate />
  </v-card>

  <v-snackbar :model-value="!!snackbar" :timeout="3000">{{ snackbar }}</v-snackbar>
</template>

// frontend-ssr/src/components/NewsDetailModal.tsx
import React, { useEffect, useState } from 'react';
import {
  Spin,
  Typography,
  Tag,
  Space,
  Divider,
  Image,
  Alert,
  Button,
  message,
} from 'antd';
import {
  ClockCircleOutlined,
  EyeOutlined,
  HeartOutlined,
  HeartFilled,
  RobotOutlined,
  LinkOutlined,
  UserOutlined,
  ShareAltOutlined,
  LikeFilled,
  LikeOutlined,
} from '@ant-design/icons';
import { newsService } from '../services/news.service';
import type { News } from '../types';
import { useUserStore } from '../store/userStoreProvider';

const { Title, Text, Paragraph } = Typography;

const NewsDetailModal: React.FC<{ newsId: string }> = ({ newsId }) => {
  const [news, setNews] = useState<News | null>(null);
  const user = useUserStore((s) => s.user);
  const [loading, setLoading] = useState(true);
  const [isFavorited, setIsFavorited] = useState(false);
  const [isLiked, setIsLiked] = useState(false);
  const [likesCount, setLikesCount] = useState(0);

  useEffect(() => {
    loadNews();
  }, [newsId]);

  const loadNews = async () => {
    setLoading(true);
    try {
      const data = await newsService.fetchById(newsId);
      setNews(data);
      setLikesCount(data.likes || 0);
    } catch {
      message.error('Ошибка загрузки новостей');
    }
    checkLike();
    checkFavorite();
    setLoading(false);
  };

  const checkLike = async () => {
    if (!user) return;
    try {
      const liked = await newsService.isLiked(newsId);
      setIsLiked(liked);
    } catch {
      message.error('Ошибка запроса checkLike');
    }
  };

  const checkFavorite = async () => {
    if (!user) return;
    try {
      const favorited = await newsService.isFavorited(newsId);
      setIsFavorited(favorited);
    } catch {
      message.error('Ошибка запроса checkFavorite');
    }
  };

  const handleLike = async () => {
    if (!user) {
      message.info('Войдите, чтобы ставить лайки');
      return;
    }
    try {
      const result = await newsService.toggleLike(newsId);
      setIsLiked(result.liked);
      setLikesCount(result.likes);
    } catch {
      message.error('Ошибка');
    }
  };

  const handleToggleFavorite = async () => {
    const token = localStorage.getItem('accessToken');
    if (!token) {
      message.info('Войдите, чтобы добавлять в избранное');
      return;
    }
    try {
      const result = await newsService.toggleFavorite(newsId);
      setIsFavorited(result.favorited);
      message.success(
        result.favorited ? 'Добавлено в избранное' : 'Удалено из избранного',
      );
    } catch {
      message.error('Ошибка');
    }
  };

  const handleShare = async () => {
    if (news) {
      const url = `${window.location.origin}/?news=${news.id}`;
      try {
        await navigator.share({ title: news.title, text: news.summary, url });
      } catch {
        await navigator.clipboard.writeText(url);
        message.success('Ссылка скопирована');
      }
    }
  };

  if (loading)
    return (
      <div style={{ textAlign: 'center', padding: 40 }}>
        <Spin size="large" />
      </div>
    );
  if (!news) return <div>Новость не найдена</div>;

  const getCategoryColor = (cat: string) => {
    const colors: Record<string, string> = {
      politics: 'blue',
      economy: 'green',
      technology: 'purple',
      science: 'cyan',
      sports: 'orange',
      entertainment: 'magenta',
      health: 'red',
      world: 'geekblue',
    };
    return colors[cat] || 'default';
  };

  const getCategoryLabel = (cat: string) => {
    const labels: Record<string, string> = {
      politics: 'Политика',
      economy: 'Экономика',
      technology: 'Технологии',
      science: 'Наука',
      sports: 'Спорт',
      entertainment: 'Развлечения',
      health: 'Здоровье',
      world: 'Мир',
    };
    return labels[cat] || cat;
  };

  return (
    <div>
      <Alert
        title={
          news.isAiGenerated
            ? '🤖 AI-рерайт новости'
            : '📄 Оригинальная новость'
        }
        description={
          news.isAiGenerated
            ? 'Эта новость создана с помощью искусственного интеллекта на основе реальных данных. Факты сохранены, формулировки изменены.'
            : 'Оригинальная новость из новостного источника.'
        }
        type={news.isAiGenerated ? 'info' : 'success'}
        showIcon
        style={{ marginBottom: 16 }}
      />
      <Title level={3}>{news.title}</Title>
      <Space wrap size="middle" style={{ marginBottom: 16, color: '#666' }}>
        <Text type="secondary">
          <ClockCircleOutlined />{' '}
          {new Date(news.publishedAt).toLocaleDateString('ru-RU', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
          })}
        </Text>
        <Text type="secondary">
          <EyeOutlined /> {news.views || 0} просмотров
        </Text>
        {news.author && (
          <Text type="secondary">
            <UserOutlined /> {news.author}
          </Text>
        )}
      </Space>

      <Space style={{ marginBottom: 16 }}>
        <Button
          icon={isLiked ? <LikeFilled /> : <LikeOutlined />}
          onClick={handleLike}
          size="small"
          danger={isLiked}
        >
          {likesCount || news.likes || 0}
        </Button>
        <Button
          icon={isFavorited ? <HeartFilled /> : <HeartOutlined />}
          onClick={handleToggleFavorite}
          size="small"
          type={isFavorited ? 'primary' : 'default'}
          danger={isFavorited}
        >
          {isFavorited ? 'В избранном' : 'В избранное'}
        </Button>
        <Button icon={<ShareAltOutlined />} onClick={handleShare} size="small">
          Поделиться
        </Button>
      </Space>

      <Space wrap style={{ marginBottom: 16 }}>
        <Tag color={getCategoryColor(news.category)}>
          {getCategoryLabel(news.category)}
        </Tag>
        {news.isAiGenerated ? (
          <Tag icon={<RobotOutlined />} color="blue">
            AI-рерайт
          </Tag>
        ) : (
          <Tag icon={<LinkOutlined />} color="green">
            Оригинал
          </Tag>
        )}
        {news.source && <Tag color="purple">{news.source}</Tag>}
        {news.tags?.map((tag) => (
          <Tag key={tag}>{tag}</Tag>
        ))}
      </Space>

      <Divider />
      {news.imageUrl && (
        <Image
          src={news.imageUrl}
          style={{
            width: '100%',
            maxHeight: 400,
            objectFit: 'cover',
            borderRadius: 8,
            marginBottom: 16,
          }}
          fallback="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="
        />
      )}
      {news.summary && (
        <Paragraph strong style={{ fontSize: 16, marginBottom: 16 }}>
          {news.summary}
        </Paragraph>
      )}
      <div
        dangerouslySetInnerHTML={{ __html: news.content }}
        style={{ fontSize: 15, lineHeight: 1.8, textAlign: 'justify' }}
      />
      {news.sourceUrl && (
        <div style={{ marginTop: 16 }}>
          <a href={news.sourceUrl} target="_blank" rel="noopener noreferrer">
            Читать оригинал на {news.source || 'источнике'}
          </a>
        </div>
      )}
    </div>
  );
};

export default NewsDetailModal;
