// frontend-next/src/components/NewsListFilters.tsx
'use client';

import { useMemo, useState } from 'react';
import { Badge, Box, Button, MenuItem, Popover, TextField, Typography } from '@mui/material';
import {
  Clear as ClearIcon,
  FilterList as FilterListIcon,
  Search as SearchIcon,
} from '@mui/icons-material';
import NewsDateRangePicker from '@/components/NewsDateRangePicker';

export type NewsListFiltersProps = {
  search: string;
  category: string;
  sortBy: string;
  aiFilter: string;
  fromDate: string;
  toDate: string;
  hasActiveFilters: boolean;
  onSearchChange: (value: string) => void;
  onSearch: () => void;
  onCategoryChange: (value: string) => void;
  onSortByChange: (value: string) => void;
  onAiFilterChange: (value: string) => void;
  onDateChange: (from: string, to: string) => void;
  onReset: () => void;
};

const categories = [
  { value: 'all', label: '📂 Все' },
  { value: 'politics', label: '🏛 Политика' },
  { value: 'economy', label: '💹 Экономика' },
  { value: 'technology', label: '💻 Технологии' },
  { value: 'science', label: '🔬 Наука' },
  { value: 'sports', label: '⚽ Спорт' },
  { value: 'entertainment', label: '🎬 Развлечения' },
  { value: 'health', label: '🏥 Здоровье' },
  { value: 'world', label: '🌍 Мир' },
];

export default function NewsListFilters({
  search,
  category,
  sortBy,
  aiFilter,
  fromDate,
  toDate,
  hasActiveFilters,
  onSearchChange,
  onSearch,
  onCategoryChange,
  onSortByChange,
  onAiFilterChange,
  onDateChange,
  onReset,
}: NewsListFiltersProps) {
  const [anchorEl, setAnchorEl] = useState<HTMLElement | null>(null);
  const filtersOpen = Boolean(anchorEl);

  const secondaryFilterCount = useMemo(
    () => [category !== 'all', aiFilter !== 'all', fromDate, toDate].filter(Boolean).length,
    [category, aiFilter, fromDate, toDate],
  );

  return (
    <Box sx={{ mb: 3, width: '100%' }}>
      <Box
        sx={{
          display: 'flex',
          flexDirection: { xs: 'column', md: 'row' },
          flexWrap: { xs: 'wrap', md: 'nowrap' },
          alignItems: { xs: 'stretch', md: 'center' },
          gap: 1.5,
          width: '100%',
        }}
      >
        <TextField
          size="small"
          placeholder="Поиск..."
          value={search}
          onChange={(e) => onSearchChange(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && onSearch()}
          slotProps={{
            input: { startAdornment: <SearchIcon sx={{ mr: 1, color: 'text.secondary' }} /> },
          }}
          sx={{
            width: '100%',
            flex: { md: '1 1 auto' },
            minWidth: 0,
          }}
        />

        <TextField
          select
          size="small"
          aria-label="Сортировка"
          value={sortBy}
          onChange={(e) => onSortByChange(e.target.value)}
          sx={{
            width: { xs: '100%', md: 180 },
            flexShrink: 0,
          }}
        >
          <MenuItem value="publishedAt">🕒 По дате</MenuItem>
          <MenuItem value="views">👁 По просмотрам</MenuItem>
          <MenuItem value="likes">❤️ По лайкам</MenuItem>
        </TextField>

        <Box
          sx={{
            display: 'flex',
            flexWrap: 'wrap',
            gap: 1,
            width: { xs: '100%', md: 'auto' },
            flexShrink: 0,
            '& .MuiButton-root': {
              flex: { xs: '1 1 auto', md: '0 0 auto' },
            },
          }}
        >
          <Badge badgeContent={secondaryFilterCount} color="primary">
            <Button
              variant={secondaryFilterCount > 0 ? 'contained' : 'outlined'}
              size="small"
              startIcon={<FilterListIcon />}
              onClick={(e) => setAnchorEl(e.currentTarget)}
            >
              Фильтры
            </Button>
          </Badge>

          {hasActiveFilters && (
            <Button size="small" startIcon={<ClearIcon />} onClick={onReset}>
              Сбросить
            </Button>
          )}
        </Box>
      </Box>

      <Popover
        open={filtersOpen}
        anchorEl={anchorEl}
        onClose={() => setAnchorEl(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
        transformOrigin={{ vertical: 'top', horizontal: 'right' }}
        slotProps={{
          paper: {
            sx: { p: 2, width: 'min(320px, calc(100vw - 32px))' },
          },
        }}
      >
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          <Box>
            <Typography variant="subtitle2" sx={{ mb: 0.5 }}>
              Категория
            </Typography>
            <TextField
              select
              size="small"
              fullWidth
              value={category}
              onChange={(e) => onCategoryChange(e.target.value)}
            >
              {categories.map((c) => (
                <MenuItem key={c.value} value={c.value}>
                  {c.label}
                </MenuItem>
              ))}
            </TextField>
          </Box>

          <Box>
            <Typography variant="subtitle2" sx={{ mb: 0.5 }}>
              Тип новости
            </Typography>
            <TextField
              select
              size="small"
              fullWidth
              value={aiFilter}
              onChange={(e) => onAiFilterChange(e.target.value)}
            >
              <MenuItem value="all">📋 Все</MenuItem>
              <MenuItem value="true">🤖 AI-рерайт</MenuItem>
              <MenuItem value="false">📄 Оригиналы</MenuItem>
            </TextField>
          </Box>

          <Box>
            <Typography variant="subtitle2" sx={{ mb: 0.5 }}>
              Дата новостей
            </Typography>
            <NewsDateRangePicker
              fromDate={fromDate}
              toDate={toDate}
              stacked
              fullWidth
              onChange={onDateChange}
            />
          </Box>
        </Box>
      </Popover>
    </Box>
  );
}

// frontend-nuxt/app/components/news/NewsListFilters.vue
<template>
  <div class="filters-root">
    <div class="filters-toolbar">
      <IconField class="filters-search">
        <InputIcon class="pi pi-search" />
        <InputText v-model="searchQuery" placeholder="Поиск..." @input="onSearchInput" />
      </IconField>

      <Dropdown
        v-model="sortBy"
        class="filters-sort"
        :options="sortOptions"
        option-label="label"
        option-value="value"
        aria-label="Сортировка"
        @change="emit('apply')"
      />

      <div class="filters-actions">
        <Button
          type="button"
          label="Фильтры"
          icon="pi pi-filter"
          :badge="secondaryFilterCount > 0 ? String(secondaryFilterCount) : undefined"
          :severity="secondaryFilterCount > 0 ? 'primary' : 'secondary'"
          @click="toggleFilters"
        />

        <OverlayPanel ref="filtersPanelRef" class="filters-panel">
          <div class="filters-panel-content">
            <div class="filter-field">
              <label class="filter-label">Категория</label>
              <Dropdown
                v-model="selectedCategory"
                :options="categories"
                option-label="label"
                option-value="value"
                placeholder="Все категории"
                show-clear
                append-to="self"
                @change="emit('apply')"
              />
            </div>

            <div class="filter-field">
              <label class="filter-label">Тип новости</label>
              <Dropdown
                v-model="aiFilter"
                :options="aiFilterOptions"
                option-label="label"
                option-value="value"
                append-to="self"
                @change="emit('apply')"
              />
            </div>

            <div class="filter-field">
              <label class="filter-label">Дата от</label>
              <DatePicker
                v-model="fromDate"
                date-format="dd.mm.yy"
                placeholder="Дата от"
                show-icon
                show-clear
                append-to="self"
                @update:model-value="emit('apply')"
              />
            </div>

            <div class="filter-field">
              <label class="filter-label">Дата до</label>
              <DatePicker
                v-model="toDate"
                date-format="dd.mm.yy"
                placeholder="Дата до"
                show-icon
                show-clear
                append-to="self"
                :min-date="fromDate ?? undefined"
                @update:model-value="emit('apply')"
              />
            </div>
          </div>
        </OverlayPanel>

        <Button
          v-if="hasActiveFilters"
          label="Сбросить"
          aria-label="Сбросить"
          icon="pi pi-filter-slash"
          severity="secondary"
          @click="emit('reset')"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { NewsCategory } from '~/types';
import { useDebounceFn } from '@vueuse/core';
import type OverlayPanel from 'primevue/overlaypanel';

const searchQuery = defineModel<string>('searchQuery', { default: '' });
const selectedCategory = defineModel<NewsCategory | null>('selectedCategory', { default: null });
const sortBy = defineModel<string>('sortBy', { default: 'publishedAt' });
const aiFilter = defineModel<'all' | 'true' | 'false'>('aiFilter', { default: 'all' });
const fromDate = defineModel<Date | null>('fromDate', { default: null });
const toDate = defineModel<Date | null>('toDate', { default: null });

defineProps<{
  hasActiveFilters: boolean;
}>();

const emit = defineEmits<{
  search: [];
  apply: [];
  reset: [];
}>();

const filtersPanelRef = ref<InstanceType<typeof OverlayPanel> | null>(null);

const categories = [
  { label: 'Политика', value: 'politics' as NewsCategory },
  { label: 'Экономика', value: 'economy' as NewsCategory },
  { label: 'Технологии', value: 'technology' as NewsCategory },
  { label: 'Наука', value: 'science' as NewsCategory },
  { label: 'Спорт', value: 'sports' as NewsCategory },
  { label: 'Развлечения', value: 'entertainment' as NewsCategory },
  { label: 'Здоровье', value: 'health' as NewsCategory },
  { label: 'Мир', value: 'world' as NewsCategory },
  { label: 'Другое', value: 'other' as NewsCategory },
];

const sortOptions = [
  { label: 'Сначала новые', value: 'publishedAt' },
  { label: 'Сначала старые', value: 'publishedAt_asc' },
  { label: 'По просмотрам', value: 'views' },
  { label: 'По лайкам', value: 'likes' },
];

const aiFilterOptions = [
  { label: 'Все', value: 'all' as const },
  { label: 'AI-рерайт', value: 'true' as const },
  { label: 'Оригиналы', value: 'false' as const },
];

const secondaryFilterCount = computed(
  () =>
    [selectedCategory.value, aiFilter.value !== 'all', fromDate.value, toDate.value].filter(Boolean)
      .length,
);

const debouncedSearch = useDebounceFn(() => {
  emit('search');
}, 500);

function onSearchInput(): void {
  debouncedSearch();
}

function toggleFilters(event: Event): void {
  filtersPanelRef.value?.toggle(event);
}
</script>

<style scoped>
.filters-root {
  width: 100%;
  margin-bottom: 2rem;
}

.filters-toolbar {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  width: 100%;
}

.filters-search {
  width: 100%;
}

.filters-search :deep(.p-inputtext) {
  width: 100%;
}

.filters-sort {
  width: 100%;
}

.filters-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  align-items: center;
}

.filters-panel-content {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  width: min(280px, calc(100vw - 2rem));
}

.filter-field {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  width: 100%;
}

.filter-label {
  font-weight: 600;
  font-size: 0.875rem;
  color: var(--p-text-color);
}

.filter-field :deep(.p-dropdown),
.filter-field :deep(.p-datepicker) {
  width: 100%;
}

@media (min-width: 768px) {
  .filters-toolbar {
    flex-direction: row;
    flex-wrap: nowrap;
    align-items: center;
  }

  .filters-search {
    flex: 1 1 auto;
    min-width: 0;
  }

  .filters-sort {
    flex: 0 0 180px;
    width: 180px;
  }

  .filters-actions {
    flex-shrink: 0;
    flex-wrap: nowrap;
  }
}

@media (max-width: 767px) {
  .filters-actions {
    width: 100%;
  }

  .filters-actions :deep(.p-button) {
    flex: 1 1 auto;
  }
}
</style>
