// frontend-vue/src/pages/admin/SuperAdminPanel.vue
<script setup lang="ts">
import { onMounted, ref, toRaw, watch } from 'vue';
import { apiClient } from '@/api/client';
import { aiService } from '@/services/ai.service';
import { newsService } from '@/services/news.service';
import { userService } from '@/services/user.service';
import type { User } from '@/types/auth';
import { NewsCategory, NewsStatus, type News } from '@/types/news';

type TableType = 'news' | 'users';
type ModalType = 'user' | 'news';

const table = ref<TableType>('news');
const news = ref<News[]>([]);
const users = ref<User[]>([]);
const loading = ref(false);
const generating = ref(false);
const editUser = ref<User | null>(null);
const editNews = ref<News | null>(null);
const editModal = ref(false);
const modalType = ref<ModalType>('user');
const deleteConfirm = ref(false);
const deleteItem = ref<{ id: string; type: ModalType }>({ id: '', type: 'news' });
const cronModal = ref(false);
const cronSchedule = ref('0 5,18 * * *');
const cronLoading = ref(false);
const snackbar = ref(false);
const snackbarMessage = ref('');
const snackbarColor = ref<'success' | 'error'>('success');

const tableOptions = [
  { title: 'Новости', value: 'news' },
  { title: 'Пользователи', value: 'users' }
];

const roleOptions = [
  { title: 'Пользователь', value: 'user' },
  { title: 'Модератор', value: 'moderator' },
  { title: 'Администратор', value: 'admin' }
];

const categoryOptions = Object.values(NewsCategory);
const statusOptions = Object.values(NewsStatus);

function showMessage(message: string, color: 'success' | 'error' = 'success') {
  snackbarMessage.value = message;
  snackbarColor.value = color;
  snackbar.value = true;
}

function formatDate(date: string) {
  return new Date(date).toLocaleDateString('ru-RU');
}

function getRoleLabel(role: string) {
  if (role === 'super_admin') return '👑 Суперадмин';
  return role;
}

function getRoleColor(role: string) {
  if (role === 'super_admin') return 'amber-darken-2';
  if (role === 'admin') return 'error';
  return 'primary';
}

async function loadNews() {
  loading.value = true;
  try {
    const response = await newsService.getNews({ limit: 100, sortBy: 'createdAt', sortOrder: 'DESC' });
    news.value = response.data;
  } catch {
    showMessage('Ошибка загрузки', 'error');
  } finally {
    loading.value = false;
  }
}

async function loadUsers() {
  loading.value = true;
  try {
    const response = await userService.getUsers(1, 100);
    users.value = response.data;
  } catch {
    showMessage('Ошибка загрузки', 'error');
  } finally {
    loading.value = false;
  }
}

async function loadTableData() {
  if (table.value === 'news') {
    await loadNews();
  } else {
    await loadUsers();
  }
}

async function loadCronSchedule() {
  try {
    const response = await aiService.getCronSchedule();
    cronSchedule.value = response.cron;
  } catch {
    // расписание по умолчанию
  }
}

function openEditNews(item: News) {
  const raw = toRaw(item);
  editNews.value = { ...raw, tags: [...raw.tags] };
  modalType.value = 'news';
  editModal.value = true;
}

function openEditUser(user: User) {
  const raw = toRaw(user);
  editUser.value = {
    ...raw,
    preferences: { ...raw.preferences }
  };
  modalType.value = 'user';
  editModal.value = true;
}

async function handleSaveUser() {
  if (!editUser.value) return;
  try {
    await userService.updateUser(editUser.value.id, {
      email: editUser.value.email,
      username: editUser.value.username,
      role: editUser.value.role,
      isActive: editUser.value.isActive
    });
    showMessage('Пользователь сохранён');
    editModal.value = false;
    await loadUsers();
  } catch {
    showMessage('Ошибка сохранения', 'error');
  }
}

async function handleSaveNews() {
  if (!editNews.value) return;
  try {
    await newsService.updateNews(editNews.value.id, {
      title: editNews.value.title,
      content: editNews.value.content,
      summary: editNews.value.summary,
      category: editNews.value.category,
      tags: editNews.value.tags,
      status: editNews.value.status,
      source: editNews.value.source,
      sourceUrl: editNews.value.sourceUrl,
      imageUrl: editNews.value.imageUrl,
      isAiGenerated: editNews.value.isAiGenerated
    });
    showMessage('Новость сохранена');
    editModal.value = false;
    await loadNews();
  } catch {
    showMessage('Ошибка сохранения', 'error');
  }
}

async function handleAutoGenerate() {
  generating.value = true;
  try {
    const result = await aiService.autoGenerate(2);
    showMessage(`Сгенерировано ${result.totalGenerated} новостей`);
    if (table.value === 'news') {
      await loadNews();
    }
  } catch {
    showMessage('Ошибка генерации', 'error');
  } finally {
    generating.value = false;
  }
}

async function handleUpdateCron() {
  cronLoading.value = true;
  try {
    await aiService.updateCronSchedule(cronSchedule.value);
    showMessage('Расписание обновлено');
    cronModal.value = false;
  } catch {
    showMessage('Ошибка обновления расписания', 'error');
  } finally {
    cronLoading.value = false;
  }
}

function confirmDelete(id: string, type: ModalType) {
  deleteItem.value = { id, type };
  deleteConfirm.value = true;
}

async function handleDelete() {
  try {
    if (deleteItem.value.type === 'news') {
      await apiClient.delete(`/news/${deleteItem.value.id}`);
      showMessage('Новость удалена');
      await loadNews();
    } else {
      await userService.deleteUser(deleteItem.value.id);
      showMessage('Пользователь удалён');
      await loadUsers();
    }
    deleteConfirm.value = false;
  } catch {
    showMessage('Ошибка удаления', 'error');
  }
}

onMounted(() => {
  loadTableData();
  loadCronSchedule();
});

watch(table, loadTableData);
</script>

<template>
  <div>
    <h3 class="text-h6 mb-4">
      <v-icon color="amber-darken-2" class="mr-2">mdi-crown</v-icon>
      Панель суперадмина
    </h3>

    <div class="d-flex flex-wrap ga-2 mb-4">
      <v-select v-model="table" :items="tableOptions" item-title="title" item-value="value" density="compact" style="max-width: 220px" hide-details />
      <v-btn color="primary" prepend-icon="mdi-rocket-launch" :loading="generating" @click="handleAutoGenerate">Сгенерировать новости</v-btn>
      <v-btn prepend-icon="mdi-clock-outline" @click="cronModal = true">Расписание</v-btn>
    </div>

    <v-progress-linear v-if="loading" indeterminate color="primary" class="mb-2" />

    <v-table v-if="table === 'news'">
      <thead>
        <tr>
          <th>Заголовок</th>
          <th>Категория</th>
          <th>Статус</th>
          <th>Дата</th>
          <th>Действия</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="item in news" :key="item.id">
          <td class="text-truncate" style="max-width: 240px">{{ item.title }}</td>
          <td><v-chip size="small">{{ item.category }}</v-chip></td>
          <td><v-chip size="small">{{ item.status }}</v-chip></td>
          <td>{{ formatDate(item.createdAt) }}</td>
          <td>
            <v-btn class="mr-1" size="x-small" icon="mdi-pencil" @click="openEditNews(item)" />
            <v-btn size="x-small" icon="mdi-delete" color="error" @click="confirmDelete(item.id, 'news')" />
          </td>
        </tr>
        <tr v-if="!loading && !news.length">
          <td colspan="5" class="text-center text-medium-emphasis py-6">Нет новостей</td>
        </tr>
      </tbody>
    </v-table>

    <v-table v-else>
      <thead>
        <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Роль</th>
          <th>Активен</th>
          <th>Действия</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="user in users" :key="user.id">
          <td>{{ user.username }}</td>
          <td>{{ user.email }}</td>
          <td>
            <v-chip size="small" :color="getRoleColor(user.role)">{{ getRoleLabel(user.role) }}</v-chip>
          </td>
          <td>{{ user.isActive ? '✅' : '❌' }}</td>
          <td>
            <template v-if="user.role !== 'super_admin'">
              <v-btn class="mr-1" size="x-small" icon="mdi-pencil" @click="openEditUser(user)" />
              <v-btn size="x-small" icon="mdi-delete" color="error" @click="confirmDelete(user.id, 'user')" />
            </template>
          </td>
        </tr>
        <tr v-if="!loading && !users.length">
          <td colspan="5" class="text-center text-medium-emphasis py-6">Нет пользователей</td>
        </tr>
      </tbody>
    </v-table>

    <v-dialog v-model="editModal" max-width="640">
      <v-card>
        <v-card-title>{{ modalType === 'user' ? 'Редактировать пользователя' : 'Редактировать новость' }}</v-card-title>
        <v-card-text>
          <template v-if="modalType === 'user' && editUser">
            <v-text-field v-model="editUser.email" label="Email" density="compact" class="mb-2" />
            <v-text-field v-model="editUser.username" label="Username" density="compact" class="mb-2" />
            <v-select v-model="editUser.role" :items="roleOptions" item-title="title" item-value="value" label="Роль" density="compact" class="mb-2" />
            <v-switch v-model="editUser.isActive" label="Активен" color="primary" />
          </template>
          <template v-if="modalType === 'news' && editNews">
            <v-text-field v-model="editNews.title" label="Заголовок" density="compact" class="mb-2" />
            <v-textarea v-model="editNews.summary" label="Краткое описание" density="compact" rows="3" class="mb-2" />
            <v-textarea v-model="editNews.content" label="Контент" density="compact" rows="6" class="mb-2" />
            <v-select v-model="editNews.category" :items="categoryOptions" label="Категория" density="compact" class="mb-2" />
            <v-select v-model="editNews.status" :items="statusOptions" label="Статус" density="compact" class="mb-2" />
            <v-text-field v-model="editNews.source" label="Источник" density="compact" class="mb-2" />
            <v-text-field v-model="editNews.sourceUrl" label="URL источника" density="compact" class="mb-2" />
            <v-text-field v-model="editNews.imageUrl" label="URL картинки" density="compact" class="mb-2" />
            <v-switch v-model="editNews.isAiGenerated" label="AI-новость" color="primary" />
          </template>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="editModal = false">Отмена</v-btn>
          <v-btn color="primary" @click="modalType === 'user' ? handleSaveUser() : handleSaveNews()">Сохранить</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-dialog v-model="cronModal" max-width="520">
      <v-card>
        <v-card-title>Настройка расписания генерации</v-card-title>
        <v-card-text>
          <v-text-field v-model="cronSchedule" label="Cron-выражение" placeholder="0 5,18 * * *" density="compact" class="mb-2" />
          <p class="text-caption text-medium-emphasis">
            Формат: минута час день месяц день_недели. Пример: 0 5,18 * * * — каждый день в 5:00 и 18:00
          </p>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="cronModal = false">Отмена</v-btn>
          <v-btn color="primary" :loading="cronLoading" @click="handleUpdateCron">Сохранить</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-dialog v-model="deleteConfirm" max-width="400">
      <v-card>
        <v-card-text>Удалить?</v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="deleteConfirm = false">Отмена</v-btn>
          <v-btn color="error" @click="handleDelete">Удалить</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-snackbar v-model="snackbar" :color="snackbarColor" :timeout="3000">{{ snackbarMessage }}</v-snackbar>
  </div>
</template>

// frontend/src/pages/admin/SuperAdminPanel.tsx
import React, { useEffect, useState } from 'react';
import { Table, Button, Tag, Space, Select, message, Popconfirm, Modal, Input, Switch } from 'antd';
import { ReadOutlined, TeamOutlined, EditOutlined, DeleteOutlined, CrownOutlined, RocketOutlined, ClockCircleOutlined } from '@ant-design/icons';
import { newsService } from '@/services/newsService';
import { userService } from '@/services/userService';
import { News, NewsStatus, NewsCategory } from '@/types/news';
import { User } from '@/types/auth';
import type { ColumnsType } from 'antd/es/table';
import { aiService } from '@/services/aiService.ts';
import { apiService } from '@/services/api.ts';

const { TextArea } = Input;

const SuperAdminPanel: React.FC = () => {
  const [table, setTable] = useState<'news' | 'users'>('news');
  const [news, setNews] = useState<News[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(false);
  const [editUser, setEditUser] = useState<User | null>(null);
  const [editNews, setEditNews] = useState<News | null>(null);
  const [modalVisible, setModalVisible] = useState(false);
  const [modalType, setModalType] = useState<'user' | 'news'>('user');
  const [generating, setGenerating] = useState(false);

  // Cron state
  const [cronModal, setCronModal] = useState(false);
  const [cronSchedule, setCronSchedule] = useState('0 5,18 * * *');
  const [cronLoading, setCronLoading] = useState(false);

  useEffect(() => {
    table === 'news' ? loadNews() : loadUsers();
  }, [table]);

  useEffect(() => {
    apiService
      .get('/ai/cron')
      .then((r) => setCronSchedule(r.data.cron))
      .catch(() => {});
  }, []);

  const loadNews = async () => {
    setLoading(true);
    try {
      const response = await newsService.getNews({ limit: 100, sortBy: 'createdAt', sortOrder: 'DESC' });
      setNews(response.data);
    } catch {
      message.error('Ошибка загрузки');
    }
    setLoading(false);
  };

  const loadUsers = async () => {
    setLoading(true);
    try {
      const response = await userService.getUsers(1, 100);
      setUsers(response.data);
    } catch {
      message.error('Ошибка загрузки');
    }
    setLoading(false);
  };

  const handleDeleteNews = async (id: string) => {
    await newsService.deleteNews(id);
    message.success('Новость удалена');
    loadNews();
  };

  const handleDeleteUser = async (id: string) => {
    await userService.deleteUser(id);
    message.success('Пользователь удален');
    loadUsers();
  };

  const handleEditUser = (user: User) => {
    setEditUser(user);
    setModalType('user');
    setModalVisible(true);
  };

  const handleEditNews = (item: News) => {
    setEditNews(item);
    setModalType('news');
    setModalVisible(true);
  };

  const handleSaveUser = async () => {
    if (!editUser) return;
    try {
      await userService.updateUser(editUser.id, {
        email: editUser.email,
        username: editUser.username,
        role: editUser.role,
        isActive: editUser.isActive,
      });
      message.success('Пользователь сохранен');
      setModalVisible(false);
      loadUsers();
    } catch {
      message.error('Ошибка сохранения');
    }
  };

  const handleSaveNews = async () => {
    if (!editNews) return;
    try {
      await newsService.updateNews(editNews.id, {
        title: editNews.title,
        content: editNews.content,
        summary: editNews.summary,
        category: editNews.category,
        tags: editNews.tags,
        status: editNews.status,
        source: editNews.source,
        sourceUrl: editNews.sourceUrl,
        imageUrl: editNews.imageUrl,
        isAiGenerated: editNews.isAiGenerated,
      });
      message.success('Новость сохранена');
      setModalVisible(false);
      loadNews();
    } catch {
      message.error('Ошибка сохранения');
    }
  };

  const handleAutoGenerate = async () => {
    setGenerating(true);
    try {
      const result = await aiService.autoGenerate(2);
      message.success(`Сгенерировано ${result.totalGenerated} новостей`);
    } catch {
      message.error('Ошибка генерации');
    }
    setGenerating(false);
  };

  const handleUpdateCron = async () => {
    setCronLoading(true);
    try {
      await apiService.put('/ai/cron', { cron: cronSchedule });
      message.success('Расписание обновлено');
      setCronModal(false);
    } catch {
      message.error('Ошибка обновления расписания');
    }
    setCronLoading(false);
  };

  const newsColumns: ColumnsType<News> = [
    { title: 'Заголовок', dataIndex: 'title', key: 'title', ellipsis: true },
    { title: 'Категория', dataIndex: 'category', key: 'category', width: 120, render: (c) => <Tag>{c}</Tag> },
    { title: 'Статус', dataIndex: 'status', key: 'status', width: 120, render: (s) => <Tag>{s}</Tag> },
    { title: 'Дата', dataIndex: 'createdAt', key: 'date', width: 110, render: (d) => new Date(d).toLocaleDateString('ru-RU') },
    {
      title: 'Действия',
      key: 'actions',
      width: 150,
      render: (_, r) => (
        <Space>
          <Button size="small" icon={<EditOutlined />} onClick={() => handleEditNews(r)} />
          <Popconfirm title="Удалить?" onConfirm={() => handleDeleteNews(r.id)}>
            <Button size="small" danger icon={<DeleteOutlined />} />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  const userColumns: ColumnsType<User> = [
    { title: 'Username', dataIndex: 'username', key: 'username' },
    { title: 'Email', dataIndex: 'email', key: 'email' },
    {
      title: 'Роль',
      dataIndex: 'role',
      key: 'role',
      width: 130,
      render: (r) => <Tag color={r === 'super_admin' ? 'gold' : r === 'admin' ? 'red' : 'blue'}>{r === 'super_admin' ? '👑 Суперадмин' : r}</Tag>,
    },
    { title: 'Активен', dataIndex: 'isActive', key: 'active', width: 80, render: (a) => (a ? '✅' : '❌') },
    {
      title: 'Действия',
      key: 'actions',
      width: 150,
      render: (_, r) => (
        <Space>
          {r.role !== 'super_admin' && <Button size="small" icon={<EditOutlined />} onClick={() => handleEditUser(r)} />}
          {r.role !== 'super_admin' && (
            <Popconfirm title="Удалить?" onConfirm={() => handleDeleteUser(r.id)}>
              <Button size="small" danger icon={<DeleteOutlined />} />
            </Popconfirm>
          )}
        </Space>
      ),
    },
  ];

  return (
    <div>
      <h2>
        <CrownOutlined style={{ color: 'gold', marginRight: 8 }} />
        Панель суперадмина
      </h2>

      <Space style={{ marginBottom: 16 }}>
        <Select value={table} onChange={setTable} style={{ width: 200 }}>
          <Select.Option value="news">
            <ReadOutlined /> Новости
          </Select.Option>
          <Select.Option value="users">
            <TeamOutlined /> Пользователи
          </Select.Option>
        </Select>
        <Button type="primary" icon={<RocketOutlined />} loading={generating} onClick={handleAutoGenerate}>
          Сгенерировать новости
        </Button>
        <Button icon={<ClockCircleOutlined />} onClick={() => setCronModal(true)}>
          Расписание
        </Button>
      </Space>

      {table === 'news' ? (
        <Table columns={newsColumns} dataSource={news} rowKey="id" loading={loading} scroll={{ x: 700 }} />
      ) : (
        <Table columns={userColumns} dataSource={users} rowKey="id" loading={loading} scroll={{ x: 700 }} />
      )}

      <Modal
        title={modalType === 'user' ? 'Редактировать пользователя' : 'Редактировать новость'}
        open={modalVisible}
        onOk={modalType === 'user' ? handleSaveUser : handleSaveNews}
        onCancel={() => setModalVisible(false)}
        width={600}
      >
        {modalType === 'user' && editUser && (
          <Space direction="vertical" style={{ width: '100%' }}>
            <Input value={editUser.email} onChange={(e) => setEditUser({ ...editUser, email: e.target.value })} placeholder="Email" />
            <Input value={editUser.username} onChange={(e) => setEditUser({ ...editUser, username: e.target.value })} placeholder="Username" />
            <Select value={editUser.role} onChange={(v) => setEditUser({ ...editUser, role: v })} style={{ width: '100%' }}>
              <Select.Option value="user">Пользователь</Select.Option>
              <Select.Option value="moderator">Модератор</Select.Option>
              <Select.Option value="admin">Админ</Select.Option>
            </Select>
            <Switch
              checked={editUser.isActive}
              onChange={(c) => setEditUser({ ...editUser, isActive: c })}
              checkedChildren="Активен"
              unCheckedChildren="Заблокирован"
            />
          </Space>
        )}
        {modalType === 'news' && editNews && (
          <Space direction="vertical" style={{ width: '100%' }}>
            <Input value={editNews.title} onChange={(e) => setEditNews({ ...editNews, title: e.target.value })} placeholder="Заголовок" />
            <TextArea
              value={editNews.summary}
              onChange={(e) => setEditNews({ ...editNews, summary: e.target.value })}
              placeholder="Краткое описание"
              rows={3}
            />
            <TextArea
              value={editNews.content}
              onChange={(e) => setEditNews({ ...editNews, content: e.target.value })}
              placeholder="Контент"
              rows={6}
            />
            <Select value={editNews.category} onChange={(v) => setEditNews({ ...editNews, category: v })} style={{ width: '100%' }}>
              {Object.values(NewsCategory).map((c) => (
                <Select.Option key={c} value={c}>
                  {c}
                </Select.Option>
              ))}
            </Select>
            <Select value={editNews.status} onChange={(v) => setEditNews({ ...editNews, status: v })} style={{ width: '100%' }}>
              {Object.values(NewsStatus).map((s) => (
                <Select.Option key={s} value={s}>
                  {s}
                </Select.Option>
              ))}
            </Select>
            <Input value={editNews.source} onChange={(e) => setEditNews({ ...editNews, source: e.target.value })} placeholder="Источник" />
            <Input value={editNews.sourceUrl} onChange={(e) => setEditNews({ ...editNews, sourceUrl: e.target.value })} placeholder="URL источника" />
            <Input value={editNews.imageUrl} onChange={(e) => setEditNews({ ...editNews, imageUrl: e.target.value })} placeholder="URL картинки" />
            <Switch
              checked={editNews.isAiGenerated}
              onChange={(c) => setEditNews({ ...editNews, isAiGenerated: c })}
              checkedChildren="AI"
              unCheckedChildren="Оригинал"
            />
          </Space>
        )}
      </Modal>

      <Modal
        title="Настройка расписания генерации"
        open={cronModal}
        onOk={handleUpdateCron}
        onCancel={() => setCronModal(false)}
        confirmLoading={cronLoading}
      >
        <Space direction="vertical" style={{ width: '100%' }}>
          <Input value={cronSchedule} onChange={(e) => setCronSchedule(e.target.value)} placeholder="0 5,18 * * *" />
          <span style={{ color: '#666', fontSize: 12 }}>
            Формат: минута час день месяц день_недели. Пример: 0 5,18 * * * — каждый день в 5:00 и 18:00
          </span>
        </Space>
      </Modal>
    </div>
  );
};

export default SuperAdminPanel;
