// frontend/src/components/FrameworkSwitcher.tsx
import React from 'react';

interface FrameworkSwitcherProps {
  current: 'react' | 'nestjs' | 'nuxt' | 'vue';
}

const frameworks = {
  react: { label: '⚛️ React SPA', url: 'https://short-news.ru' },
  vue: { label: '🟢 Vue SPA', url: 'https://vue.short-news.ru' },
  next: { label: '🔵 Next.js', url: 'https://next.short-news.ru' },
  nuxt: { label: '🟣 Nuxt', url: 'https://nuxt.short-news.ru' },
  // nestjs: { label: '🟢 NestJS SSR + React', url: 'https://nest.short-news.ru' },
};

const FrameworkSwitcher: React.FC<FrameworkSwitcherProps> = ({ current }) => {
  const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const value = e.target.value as keyof typeof frameworks;
    if (value !== current && frameworks[value].url !== '#') {
      window.location.href = frameworks[value].url;
    }
  };

  return (
    <select
      value={current}
      onChange={handleChange}
      aria-label="Выбор фреймворка"
      style={{
        padding: '6px 12px',
        borderRadius: 6,
        border: '1px solid #6c5ce7',
        background: '#1a1a2e',
        color: '#fff',
        fontSize: 13,
        cursor: 'pointer',
        outline: 'none',
        fontFamily: 'inherit',
      }}
    >
      {Object.entries(frameworks).map(([key, { label }]) => (
        <option key={key} value={key}>
          {label}
        </option>
      ))}
    </select>
  );
};

export default FrameworkSwitcher;

// frontend-vue/src/components/common/FrameworkSwitcher.vue
<script setup lang="ts">
defineProps<{
  current: 'react' | 'vue' | 'next' | 'nuxt';
}>();

const frameworks = {
  react: { label: '⚛️ React SPA', url: 'https://short-news.ru' },
  vue: { label: '💚 Vue SPA', url: 'https://vue.short-news.ru' },
  next: { label: '🔵 Next.js', url: 'https://next.short-news.ru' },
  nuxt: { label: '🟣 Nuxt', url: 'https://nuxt.short-news.ru' }
};

function onChange(event: Event) {
  const value = (event.target as HTMLSelectElement).value as keyof typeof frameworks;
  if (value && frameworks[value]) {
    window.location.href = frameworks[value].url;
  }
}
</script>

<template>
  <select :value="current" class="framework-select" aria-label="Выбор фреймворка" @change="onChange">
    <option v-for="(fw, key) in frameworks" :key="key" :value="key">
      {{ fw.label }}
    </option>
  </select>
</template>

<style scoped>
.framework-select {
  padding: 6px 12px;
  border-radius: 6px;
  border: 1px solid #6c5ce7;
  background: #1a1a2e;
  color: #fff;
  font-size: 13px;
  cursor: pointer;
  outline: none;
}
</style>
