// frontend-vue/src/components/news/NewsListFilters.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

const search = defineModel<string>('search', { default: '' });
const category = defineModel<string>('category', { default: 'all' });
const sortBy = defineModel<string>('sortBy', { default: 'publishedAt' });
const aiFilter = defineModel<string>('aiFilter', { default: 'all' });
const fromDate = defineModel<string>('fromDate', { default: '' });
const toDate = defineModel<string>('toDate', { default: '' });

defineProps<{
  hasActiveFilters: boolean;
  categories: Array<{ value: string; label: string }>;
}>();

const emit = defineEmits<{
  search: [];
  reset: [];
}>();

const filtersMenuOpen = ref(false);

const sortOptions = [
  { value: 'publishedAt', title: '🕒 По дате' },
  { value: 'views', title: '👁 По просмотрам' },
  { value: 'likes', title: '❤️ По лайкам' }
];

const aiFilterOptions = [
  { value: 'all', title: '📋 Все' },
  { value: 'true', title: '🤖 AI-рерайт' },
  { value: 'false', title: '📄 Оригиналы' }
];

const secondaryFilterCount = computed(() => [category.value !== 'all', aiFilter.value !== 'all', !!fromDate.value, !!toDate.value].filter(Boolean).length);

const selectMenuProps = { zIndex: 2500 };
</script>

<template>
  <div :class="$style.root">
    <div :class="$style.toolbar">
      <v-text-field
        v-model="search"
        :class="$style.search"
        label="Поиск..."
        density="compact"
        hide-details
        prepend-inner-icon="mdi-magnify"
        clearable
        @keydown.enter="emit('search')"
        @click:clear="emit('search')"
      />

      <v-select v-model="sortBy" :class="$style.sort" :items="sortOptions" density="compact" hide-details aria-label="Сортировка" />

      <div :class="$style.toolbarActions">
        <v-menu v-model="filtersMenuOpen" :close-on-content-click="false" location="bottom end">
          <template #activator="{ props: menuProps }">
            <v-badge :content="secondaryFilterCount" :model-value="secondaryFilterCount > 0" color="primary">
              <v-btn v-bind="menuProps" :variant="secondaryFilterCount > 0 ? 'flat' : 'outlined'" color="primary" prepend-icon="mdi-filter"> Фильтры </v-btn>
            </v-badge>
          </template>

          <v-card :class="$style.panel" min-width="280">
            <v-card-text :class="$style.panelContent">
              <div :class="$style.field">
                <span :class="$style.label">Категория</span>
                <v-select v-model="category" :items="categories" item-value="value" item-title="label" density="compact" hide-details :menu-props="selectMenuProps" />
              </div>

              <div :class="$style.field">
                <span :class="$style.label">Тип новости</span>
                <v-select v-model="aiFilter" :items="aiFilterOptions" density="compact" hide-details :menu-props="selectMenuProps" />
              </div>

              <div :class="$style.field">
                <span :class="$style.label">Дата от</span>
                <v-text-field v-model="fromDate" type="date" density="compact" hide-details />
              </div>

              <div :class="$style.field">
                <span :class="$style.label">Дата до</span>
                <v-text-field v-model="toDate" type="date" density="compact" hide-details :min="fromDate || undefined" />
              </div>
            </v-card-text>
          </v-card>
        </v-menu>

        <v-btn v-if="hasActiveFilters" variant="outlined" color="primary" prepend-icon="mdi-filter-off" @click="emit('reset')"> Сбросить </v-btn>
      </div>
    </div>
  </div>
</template>

<style module>
.root {
  width: 100%;
  margin-bottom: 16px;
}

.toolbar {
  display: flex;
  flex-direction: column;
  gap: 12px;
  width: 100%;
}

.search {
  width: 100%;
}

.sort {
  width: 100%;
  min-width: 0;
}

.toolbarActions {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  align-items: center;
}

.panel {
  max-width: min(320px, calc(100vw - 32px));
}

.panelContent {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px !important;
}

.field {
  width: 100%;
  min-width: 0;
}

.label {
  display: block;
  margin-bottom: 4px;
  font-size: 0.875rem;
  font-weight: 600;
}

@media (min-width: 768px) {
  .toolbar {
    flex-direction: row;
    flex-wrap: nowrap;
    align-items: center;
  }

  .search {
    flex: 1 1 auto;
    min-width: 0;
  }

  .sort {
    flex: 0 0 180px;
    width: 180px;
  }

  .toolbarActions {
    flex-shrink: 0;
    flex-wrap: nowrap;
  }
}

@media (max-width: 767px) {
  .toolbarActions {
    width: 100%;
  }

  .toolbarActions :global(.v-btn) {
    flex: 1 1 auto;
  }
}
</style>

// frontend-next/src/components/NewsListFilters.tsx
'use client';

import { useMemo, useState } from 'react';
import { Badge, Box, Button, MenuItem, Popover, TextField, Typography } from '@mui/material';
import {
  Clear as ClearIcon,
  FilterList as FilterListIcon,
  Search as SearchIcon,
} from '@mui/icons-material';
import NewsDateRangePicker from '@/components/NewsDateRangePicker';

export type NewsListFiltersProps = {
  search: string;
  category: string;
  sortBy: string;
  aiFilter: string;
  fromDate: string;
  toDate: string;
  hasActiveFilters: boolean;
  onSearchChange: (value: string) => void;
  onSearch: () => void;
  onCategoryChange: (value: string) => void;
  onSortByChange: (value: string) => void;
  onAiFilterChange: (value: string) => void;
  onDateChange: (from: string, to: string) => void;
  onReset: () => void;
};

const categories = [
  { value: 'all', label: '📂 Все' },
  { value: 'politics', label: '🏛 Политика' },
  { value: 'economy', label: '💹 Экономика' },
  { value: 'technology', label: '💻 Технологии' },
  { value: 'science', label: '🔬 Наука' },
  { value: 'sports', label: '⚽ Спорт' },
  { value: 'entertainment', label: '🎬 Развлечения' },
  { value: 'health', label: '🏥 Здоровье' },
  { value: 'world', label: '🌍 Мир' },
];

export default function NewsListFilters({
  search,
  category,
  sortBy,
  aiFilter,
  fromDate,
  toDate,
  hasActiveFilters,
  onSearchChange,
  onSearch,
  onCategoryChange,
  onSortByChange,
  onAiFilterChange,
  onDateChange,
  onReset,
}: NewsListFiltersProps) {
  const [anchorEl, setAnchorEl] = useState<HTMLElement | null>(null);
  const filtersOpen = Boolean(anchorEl);

  const secondaryFilterCount = useMemo(
    () => [category !== 'all', aiFilter !== 'all', fromDate, toDate].filter(Boolean).length,
    [category, aiFilter, fromDate, toDate],
  );

  return (
    <Box sx={{ mb: 3, width: '100%' }}>
      <Box
        sx={{
          display: 'flex',
          flexDirection: { xs: 'column', md: 'row' },
          flexWrap: { xs: 'wrap', md: 'nowrap' },
          alignItems: { xs: 'stretch', md: 'center' },
          gap: 1.5,
          width: '100%',
        }}
      >
        <TextField
          size="small"
          placeholder="Поиск..."
          value={search}
          onChange={(e) => onSearchChange(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && onSearch()}
          slotProps={{
            input: { startAdornment: <SearchIcon sx={{ mr: 1, color: 'text.secondary' }} /> },
          }}
          sx={{
            width: '100%',
            flex: { md: '1 1 auto' },
            minWidth: 0,
          }}
        />

        <TextField
          select
          size="small"
          aria-label="Сортировка"
          value={sortBy}
          onChange={(e) => onSortByChange(e.target.value)}
          sx={{
            width: { xs: '100%', md: 180 },
            flexShrink: 0,
          }}
        >
          <MenuItem value="publishedAt">🕒 По дате</MenuItem>
          <MenuItem value="views">👁 По просмотрам</MenuItem>
          <MenuItem value="likes">❤️ По лайкам</MenuItem>
        </TextField>

        <Box
          sx={{
            display: 'flex',
            flexWrap: 'wrap',
            gap: 1,
            width: { xs: '100%', md: 'auto' },
            flexShrink: 0,
            '& .MuiButton-root': {
              flex: { xs: '1 1 auto', md: '0 0 auto' },
            },
          }}
        >
          <Badge badgeContent={secondaryFilterCount} color="primary">
            <Button
              variant={secondaryFilterCount > 0 ? 'contained' : 'outlined'}
              size="small"
              startIcon={<FilterListIcon />}
              onClick={(e) => setAnchorEl(e.currentTarget)}
            >
              Фильтры
            </Button>
          </Badge>

          {hasActiveFilters && (
            <Button size="small" startIcon={<ClearIcon />} onClick={onReset}>
              Сбросить
            </Button>
          )}
        </Box>
      </Box>

      <Popover
        open={filtersOpen}
        anchorEl={anchorEl}
        onClose={() => setAnchorEl(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
        transformOrigin={{ vertical: 'top', horizontal: 'right' }}
        slotProps={{
          paper: {
            sx: { p: 2, width: 'min(320px, calc(100vw - 32px))' },
          },
        }}
      >
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          <Box>
            <Typography variant="subtitle2" sx={{ mb: 0.5 }}>
              Категория
            </Typography>
            <TextField
              select
              size="small"
              fullWidth
              value={category}
              onChange={(e) => onCategoryChange(e.target.value)}
            >
              {categories.map((c) => (
                <MenuItem key={c.value} value={c.value}>
                  {c.label}
                </MenuItem>
              ))}
            </TextField>
          </Box>

          <Box>
            <Typography variant="subtitle2" sx={{ mb: 0.5 }}>
              Тип новости
            </Typography>
            <TextField
              select
              size="small"
              fullWidth
              value={aiFilter}
              onChange={(e) => onAiFilterChange(e.target.value)}
            >
              <MenuItem value="all">📋 Все</MenuItem>
              <MenuItem value="true">🤖 AI-рерайт</MenuItem>
              <MenuItem value="false">📄 Оригиналы</MenuItem>
            </TextField>
          </Box>

          <Box>
            <Typography variant="subtitle2" sx={{ mb: 0.5 }}>
              Дата новостей
            </Typography>
            <NewsDateRangePicker
              fromDate={fromDate}
              toDate={toDate}
              stacked
              fullWidth
              onChange={onDateChange}
            />
          </Box>
        </Box>
      </Popover>
    </Box>
  );
}
